#server
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 30
    min-spare-threads: 10

#spring
spring:
  datasource:
    url: jdbc:mysql://www.bingboy.xyz:9306/dbsys?serverTimezone=GMT
    username: bingboy
    password: 1215
    hikari:
      connection-timeout: 300
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html


#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

#lOG
logging:
  level:
    com.hb: DEBUG